language: php

php:
  - 5.4
  - 5.5
  - hhvm

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev
  - sh -c "if [ \"$TRAVIS_PHP_VERSION\" != \"hhvm\" ]; then echo \"extension = mongo.so\nextension = redis.so\" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi"
  - phpenv rehash

script:
  - phpunit -v --colors --coverage-text --coverage-clover ./build/log/clover.xml

after_script:
  - php vendor/bin/coveralls -v

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true

notifications:
  email:
    - volny.licvin@gmail.com
